version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ttapp
hooks:
    BeforeInstall:
        - location: /bin/true
    AfterInstall:
        - location: setup-symfony.sh
        - timeout: 30
