version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ttapp
hooks:
   BeforeInstall:
     - location: delete-application.sh
       timeout: 180
   AfterInstall:
     - location: setup-symfony.sh
       timeout: 180
